### ISSUE TITLE
Console.WriteLine

### ISSUE THREAD

**Issue by txdv** [ProjectMagma/Magma#79]
I know the lib is new, I'm just leaving this here as a tick off todo for the future :)

https://github.com/ProjectMagma/Magma/blob/9cd6f756595cabf6ddd284af2f99b39fe0603ac4/src/Magma.Transport.Tcp/TcpConnection.cs#L93

**Comment by Drawaes** [comment]
;) Don't worry Console.Writeline will be searched and destroyed before it gets anyway near use ...
