### ISSUE TITLE
Missing libc

### ISSUE THREAD

**Issue by Rinsen** [ProjectMagma/Magma#81]
First of all, awesome work!

What libc implementation should I use? 

Do you have some small quick get started for newbs that would like to explore a bit? :) 

System.DllNotFoundException: 'Unable to load DLL 'libc' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

In Open.cs on line 15
var fd = Open("/dev/netmap", OpenFlags.O_RDWR);

**Comment by Drawaes** [comment]
What OS are you trying to run this on?

**Comment by Rinsen** [comment]
Good to know of course :-)
Windows 10

**Comment by benaadams** [comment]
There are some outdated instructions for netmap on windows https://github.com/luigirizzo/netmap/tree/master/WINDOWS but we haven't tried it

At the moment we are working with Ubuntu16.04 VMs via Hyper-V there are some instructions here: [Ubuntu16.04.txt](https://github.com/ProjectMagma/Magma/blob/master/docker/Ubuntu16.04.txt)

Its also probably better working in a VM while its experimental as it might break the OS it this experimental stage,,,

**Comment by benaadams** [comment]
After following the instructions; and also installing dotnet 2.1 on the VM you should be able to 
```
dotnet run -c Release
```
the plaintext app https://github.com/ProjectMagma/Magma/tree/master/sample/Magma.NetMap.PlaintextApp

Then browse to it via your Windows machine via the virtual network (use `ifconfig` in the linux VM to find out what its ip address is)

**Comment by Rinsen** [comment]
Thanks! Will definitely go for the Ubuntu virtual machine option then 😊
