### ISSUE TITLE
 '/bin/sh -c modprobe netmap' returned a non-zero code: 127

### ISSUE THREAD

**Issue by itssivashankar** [ProjectMagma/Magma#88]
Hi,
while building the docker file i am getting this error

/bin/sh: 1: modprobe: not found
The command '/bin/sh -c modprobe netmap' returned a non-zero code: 127

**Comment by Drawaes** [comment]
As docker uses kernel modules from the host kernel I suspect netmap would need to be installed in the host.

**Comment by itssivashankar** [comment]
Thanks for your reply
